{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-ecommerce.fullname" . }}-mongodb
  labels:
    {{- include "mern-ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mern-ecommerce.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "mern-ecommerce.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        ports:
        - name: mongodb
          containerPort: 27017
          protocol: TCP
        {{- if .Values.mongodb.persistence.enabled }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        {{- end }}
      {{- if .Values.mongodb.persistence.enabled }}
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: {{ include "mern-ecommerce.fullname" . }}-mongodb-pvc
      {{- end }}
{{- end }}