apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mern-ecommerce.fullname" . }}-secrets
  labels:
    {{- include "mern-ecommerce.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  razorpay-key-id: {{ .Values.secrets.razorpay.keyId | b64enc | quote }}
  razorpay-key-secret: {{ .Values.secrets.razorpay.keySecret | b64enc | quote }}
  email-user: {{ .Values.secrets.email.user | b64enc | quote }}
  email-pass: {{ .Values.secrets.email.pass | b64enc | quote }}
  email-from: {{ .Values.secrets.email.from | b64enc | quote }}
  {{- if .Values.secrets.aws.accessKeyId }}
  aws-access-key-id: {{ .Values.secrets.aws.accessKeyId | b64enc | quote }}
  aws-secret-access-key: {{ .Values.secrets.aws.secretAccessKey | b64enc | quote }}
  aws-region: {{ .Values.secrets.aws.region | b64enc | quote }}
  s3-bucket-name: {{ .Values.secrets.aws.s3BucketName | b64enc | quote }}
  {{- end }}