apiVersion: v1
kind: Service
metadata:
  name: {{ include "mern-ecommerce.fullname" . }}-backend
  labels:
    {{- include "mern-ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mern-ecommerce.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mern-ecommerce.fullname" . }}-frontend
  labels:
    {{- include "mern-ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mern-ecommerce.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mern-ecommerce.fullname" . }}-mongodb
  labels:
    {{- include "mern-ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "mern-ecommerce.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}